pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        // stage('Prepare') {
        //     steps {
        //         sh "npm install yarn"
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         sh 'yarn install'
        //     }
        // }
        stage('Deliver') {
            steps {
                sh 'chmod -R 777 ./jenkins/scripts'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}